### ISSUE TITLE
Ability to analyse / evaluate snippets of code

### ISSUE THREAD

**Issue by lgalabru** [MarvinJanssen/lumio#1]
Hi Marvin, this tool looks cool! What is the use case you have in mind? Is it for learning?
I think a cool feature would be to add the ability to analyse / evaluate the contract being built, so that users know that they are building legit contracts.
This can easily be achieved with the Clarity REPL - https://github.com/lgalabru/clarity-repl.
This REPL can be executed from your browser (via WASM, demo here https://lgalabru.github.io/clarity-repl/), you can check-out the JS glue code (mostly generated) does not looks great, but it's pretty straightforward: 
https://github.com/lgalabru/clarity-repl/blob/73e6033702d5883f6c5776f4362ed8b2fb625921/docs/index.html#L141

**Comment by MarvinJanssen** [comment]
Hi Ludo, thank you! Correct: guided learning, interactive tutorials. I implemented a basic validator but hooking into the REPL is definitely on the road-map. I looked at it before but decided to forego it at the time due to time constraints. Thank you for the pointers, that looks easy enough.
